### ISSUE TITLE
Knight rider mode fails

### ISSUE THREAD

**Issue by dominicgs** [GravesJake/GreatFET-testpanel#1]
Probably caused by the refactoring, should just need an import moved:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.5/tkinter/__init__.py", line 1562, in __call__
    return self.func(*args)
  File "./testpanel.py", line 265, in knight_rider
    time.sleep(0.1)
NameError: name 'time' is not defined
```

**Comment by mnaberez** [comment]
Running `pyflakes` finds this bug and some other imports that can be cleaned up.

```
$ pyflakes .
./hardware.py:3: 'greatfet.GreatFET' imported but unused
./hardware.py:5: 'greatfet.protocol.vendor_requests' imported but unused
./hardware.py:27: local variable 'state' is assigned to but never used
./testpanel.py:4: 'sys' imported but unused
./testpanel.py:8: 'from tkinter.tix import *' used; unable to detect undefined names
./testpanel.py:9: 'tkinter.messagebox.showinfo' imported but unused
./testpanel.py:11: 'PIL.ImageTk' imported but unused
./testpanel.py:11: 'PIL.Image' imported but unused
./testpanel.py:37: local variable 'toolbar' is assigned to but never used
./testpanel.py:267: 'time' may be undefined, or defined from star imports: tkinter.tix
./testpanel.py:415: local variable 'p' is assigned to but never used
```

**Comment by grvvy** [comment]
RIP Knight Rider
